//****************************************************************************
// FontInfo.c
//
// Created 11/29/2020 10:21:49 AM by Tim
//
//****************************************************************************


#include <standard.h>
#include "FontInfo.h"


//****************************************************************************
// Define fonts using macros generated by FontGenerator

#define START_FONT_INIT(name)	const FontInfo name = {
#define END_FONT_INIT(name)		};

#define FONT_START_OFFSET(val)	.FontStart = val,
#define CHARSET_WIDTH(val)		.CharsetWidth = val,
#define CHAR_HEIGHT(val)		.Height = val,
#define FIRST_CHAR(val)			.FirstChar = val,
#define LAST_CHAR(val)			.LastChar = val,
#define CHAR_STRIDE(val)		.CharStride = val,
#define START_CHAR_WIDTHS(name)	{
#define CHAR_WIDTH(val)			val,
#define END_CHAR_WIDTHS(name)	}

// Run the macros
#include "Images/BigFont.h"


//****************************************************************************
// Make array of pointers to fonts

#define START_FONT_INIT(name)	&name,

const FontInfo *FontList[] = 
{
#include "Images/BigFont.h"
};
