//****************************************************************************
// SamUsbDevice.h
//
// Created 8/20/2020 3:44:11 PM by Tim
//
// This file contains constant declarations missing from sam.h
//
//****************************************************************************

#pragma once

enum DeviceEpType
{
	USB_DEVICE_EPCFG_EPTYPE_DISABLE_Val,
	USB_DEVICE_EPCFG_EPTYPE_CONTROL_Val,
	USB_DEVICE_EPCFG_EPTYPE_ISOCHRONOUS_Val,
	USB_DEVICE_EPCFG_EPTYPE_BULK_Val,
	USB_DEVICE_EPCFG_EPTYPE_INTERRUPT_Val,
	USB_DEVICE_EPCFG_EPTYPE_DUAL_BANK_Val
};

enum EndpointSize
{
	USB_DEVICE_PCKSIZE_SIZE_8_Val,
	USB_DEVICE_PCKSIZE_SIZE_16_Val,
	USB_DEVICE_PCKSIZE_SIZE_32_Val,
	USB_DEVICE_PCKSIZE_SIZE_64_Val,
	USB_DEVICE_PCKSIZE_SIZE_128_Val,
	USB_DEVICE_PCKSIZE_SIZE_256_Val,
	USB_DEVICE_PCKSIZE_SIZE_512_Val,
	USB_DEVICE_PCKSIZE_SIZE_1023_Val
};

#define USB_DEVICE_EPCFG_EPTYPE0_DISABLE		USB_DEVICE_EPCFG_EPTYPE0(USB_DEVICE_EPCFG_EPTYPE_DISABLE_Val)
#define USB_DEVICE_EPCFG_EPTYPE0_CONTROL		USB_DEVICE_EPCFG_EPTYPE0(USB_DEVICE_EPCFG_EPTYPE_CONTROL_Val)
#define USB_DEVICE_EPCFG_EPTYPE0_ISOCHRONOUS	USB_DEVICE_EPCFG_EPTYPE0(USB_DEVICE_EPCFG_EPTYPE_ISOCHRONOUS_Val)
#define USB_DEVICE_EPCFG_EPTYPE0_BULK			USB_DEVICE_EPCFG_EPTYPE0(USB_DEVICE_EPCFG_EPTYPE_BULK_Val)
#define USB_DEVICE_EPCFG_EPTYPE0_INTERRUPT		USB_DEVICE_EPCFG_EPTYPE0(USB_DEVICE_EPCFG_EPTYPE_INTERRUPT_Val)
#define USB_DEVICE_EPCFG_EPTYPE0_DUAL_BANK		USB_DEVICE_EPCFG_EPTYPE0(USB_DEVICE_EPCFG_EPTYPE_DUAL_BANK_Val)

#define USB_DEVICE_EPCFG_EPTYPE1_DISABLE		USB_DEVICE_EPCFG_EPTYPE1(USB_DEVICE_EPCFG_EPTYPE_DISABLE_Val)
#define USB_DEVICE_EPCFG_EPTYPE1_CONTROL		USB_DEVICE_EPCFG_EPTYPE1(USB_DEVICE_EPCFG_EPTYPE_CONTROL_Val)
#define USB_DEVICE_EPCFG_EPTYPE1_ISOCHRONOUS	USB_DEVICE_EPCFG_EPTYPE1(USB_DEVICE_EPCFG_EPTYPE_ISOCHRONOUS_Val)
#define USB_DEVICE_EPCFG_EPTYPE1_BULK			USB_DEVICE_EPCFG_EPTYPE1(USB_DEVICE_EPCFG_EPTYPE_BULK_Val)
#define USB_DEVICE_EPCFG_EPTYPE1_INTERRUPT		USB_DEVICE_EPCFG_EPTYPE1(USB_DEVICE_EPCFG_EPTYPE_INTERRUPT_Val)
#define USB_DEVICE_EPCFG_EPTYPE1_DUAL_BANK		USB_DEVICE_EPCFG_EPTYPE1(USB_DEVICE_EPCFG_EPTYPE_DUAL_BANK_Val)

#define USB_DEVICE_PCKSIZE_SIZE_8				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_8_Val)
#define USB_DEVICE_PCKSIZE_SIZE_16				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_16_Val)
#define USB_DEVICE_PCKSIZE_SIZE_32				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_32_Val)
#define USB_DEVICE_PCKSIZE_SIZE_64				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_64_Val)
#define USB_DEVICE_PCKSIZE_SIZE_128				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_128_Val)
#define USB_DEVICE_PCKSIZE_SIZE_256				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_256_Val)
#define USB_DEVICE_PCKSIZE_SIZE_512				USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_512_Val)
#define USB_DEVICE_PCKSIZE_SIZE_1023			USB_DEVICE_PCKSIZE_SIZE(USB_DEVICE_PCKSIZE_SIZE_1023_Val)
